version: "3.8"
services:
  curriculum-vitae:
    container_name: curriculum-vitae
    build:
      context: .
      target: dev
    command: yarn dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - ${CLIENT_PORT}:3000
